import jsPDF from 'jspdf';
import logoUrl from '../assets/tcj_logo.png?url';

// ==========================================
// 1. CONFIG & THEME
// ==========================================
const THEME = {
  primary: '#2c3e50',    // Dark Slate Blue (Headers)
  secondary: '#34495e',  // Lighter Blue (Subheaders)
  accent: '#f1f5f9',     // Very Light Grey (Zebra stripes)
  text: '#333333',       // Dark Grey (Body text)
  lightText: '#7f8c8d',  // Grey (Metadata)
  white: '#ffffff',
  line: '#e2e8f0',       // Light border color
};

const LAYOUT = {
  marginX: 15,
  lineHeight: 6,
  headerHeight: 8,
  pageWidth: 210, // A4 width in mm
};

// ==========================================
// 2. HELPERS
// ==========================================

const loadImageAsDataURL = async (url) => {
  try {
    const res = await fetch(url);
    const blob = await res.blob();
    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
};

const formatCurrency = (amount) => {
  const num = Number(amount) || 0;
  return `PHP ${num.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

const formatDate = (dateString) => {
  if (!dateString) return 'N/A';
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric'
  });
};

// Helper: Draw Report Header with Logo and Title
const drawReportHeader = (doc, title, subtitle, logoDataUrl) => {
  let y = 15;
  const centerX = LAYOUT.pageWidth / 2;

  if (logoDataUrl) {
    const imgWidth = 25;
    const imgHeight = 18;
    // Center the logo
    doc.addImage(logoDataUrl, 'PNG', (LAYOUT.pageWidth - imgWidth) / 2, y, imgWidth, imgHeight);
    y += imgHeight + 8;
  } else {
    y += 10;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(THEME.primary);
  doc.text(title, centerX, y, { align: 'center' });
  
  y += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(THEME.lightText);
  doc.text(subtitle, centerX, y, { align: 'center' });

  return y + 15; // Return new Y position
};

// Helper: Draw Footer
const drawFooter = (doc, adminName) => {
  const pageCount = doc.internal.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const footerY = 285;

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(THEME.line);
    doc.line(LAYOUT.marginX, footerY - 5, pageWidth - LAYOUT.marginX, footerY - 5);
    
    doc.setFontSize(8);
    doc.setTextColor(THEME.lightText);
    doc.text(`Generated by: ${adminName}`, LAYOUT.marginX, footerY);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, LAYOUT.marginX, footerY + 4);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - LAYOUT.marginX, footerY, { align: 'right' });
  }
};

// ==========================================
// 3. REPORTS
// ==========================================

// --- SALES REPORT ---
export const generateSalesReportPDF = async (salesData, startDate, endDate, adminName, rangeLabel = 'Daily') => {
  const doc = new jsPDF();
  const logoDataUrl = await loadImageAsDataURL(logoUrl);
  
  // 1. Header
  let yPos = drawReportHeader(doc, 'Sales Report', `Period: ${formatDate(startDate)} - ${formatDate(endDate)}`, logoDataUrl);

  // 2. Process Data
  const filteredOrders = salesData || [];
  const allowedStatuses = ['Completed', 'Partially Returned', 'Pending', null];
  const flattenedData = filteredOrders.flatMap(order =>
    order.items.filter(item => allowedStatuses.includes(order.status)).map(item => ({
      date: formatDate(order.orderDate),
      name: item.productName,
      qty: Number(item.quantity) || 0,
      price: Number(item.unitPrice) || 0,
      total: Number(item.totalPrice) || 0
    }))
  );

  // 3. Table Config (Note the ALIGN property)
  const cols = {
    date: { x: 15, w: 30, align: 'left' },
    name: { x: 45, w: 80, align: 'left' },
    qty: { x: 135, w: 15, align: 'right' },
    price: { x: 165, w: 25, align: 'right' },
    total: { x: 195, w: 0, align: 'right' } // x is the right anchor
  };

  // 4. Draw Table Header
  const drawHeader = (y) => {
    doc.setFillColor(THEME.primary);
    doc.rect(15, y, 180, 8, 'F'); // Header Background
    doc.setTextColor(THEME.white);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    
    // Add some padding to Y (y + 5) for vertical centering
    doc.text('Date', cols.date.x + 2, y + 5.5);
    doc.text('Product Name', cols.name.x, y + 5.5);
    doc.text('Qty', cols.qty.x, y + 5.5, { align: 'right' });
    doc.text('Unit Price', cols.price.x, y + 5.5, { align: 'right' });
    doc.text('Total', cols.total.x, y + 5.5, { align: 'right' });
  };

  drawHeader(yPos);
  yPos += 8;

  // 5. Draw Rows
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  
  let grandTotal = 0;

  flattenedData.forEach((item, index) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
      drawHeader(yPos);
      yPos += 8;
      doc.setFont('helvetica', 'normal'); 
      doc.setFontSize(9); 
    }

    // Zebra Striping
    if (index % 2 === 0) {
      doc.setFillColor(THEME.accent);
      doc.rect(15, yPos, 180, 7, 'F');
    }

    doc.setTextColor(THEME.text);
    
    // Truncate Name
    const name = item.name.length > 40 ? item.name.substring(0, 37) + '...' : item.name;

    doc.text(item.date, cols.date.x + 2, yPos + 5);
    doc.text(name, cols.name.x, yPos + 5);
    doc.text(item.qty.toString(), cols.qty.x, yPos + 5, { align: 'right' });
    doc.text(formatCurrency(item.price), cols.price.x, yPos + 5, { align: 'right' });
    doc.text(formatCurrency(item.total), cols.total.x, yPos + 5, { align: 'right' });

    grandTotal += item.total;
    yPos += 7;
  });

  // 6. Grand Total Line
  yPos += 2;
  doc.setDrawColor(THEME.primary);
  doc.setLineWidth(0.5);
  doc.line(130, yPos, 195, yPos); // Short line above total
  yPos += 6;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(THEME.primary);
  doc.text('Grand Total:', 160, yPos, { align: 'right' });
  doc.text(formatCurrency(grandTotal), 195, yPos, { align: 'right' });

  // 7. Summary Section
  yPos += 15;
  if (yPos > 250) { doc.addPage(); yPos = 20; }

  // Summary Box
  doc.setFillColor(THEME.accent);
  doc.setDrawColor(THEME.line);
  doc.roundedRect(15, yPos, 180, 35, 2, 2, 'FD');
  
  doc.setFontSize(12);
  doc.setTextColor(THEME.primary);
  doc.text('Performance Summary', 20, yPos + 8);
  
  doc.setFontSize(9);
  doc.setTextColor(THEME.text);
  doc.setFont('helvetica', 'normal');

  // Calculations
  const totalTransactions = filteredOrders.length;
  const totalItems = flattenedData.reduce((acc, i) => acc + i.qty, 0);
  const avgValue = totalTransactions ? grandTotal / totalTransactions : 0;
  
  // Left Column
  let sumY = yPos + 16;
  doc.text(`Total Revenue:`, 20, sumY);
  doc.setFont('helvetica', 'bold');
  doc.text(formatCurrency(grandTotal), 60, sumY);
  
  sumY += 6;
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Transactions:`, 20, sumY);
  doc.setFont('helvetica', 'bold');
  doc.text(totalTransactions.toString(), 60, sumY);

  // Right Column
  sumY = yPos + 16;
  doc.setFont('helvetica', 'normal');
  doc.text(`Items Sold:`, 110, sumY);
  doc.setFont('helvetica', 'bold');
  doc.text(totalItems.toString(), 150, sumY);

  sumY += 6;
  doc.setFont('helvetica', 'normal');
  doc.text(`Avg Ticket Value:`, 110, sumY);
  doc.setFont('helvetica', 'bold');
  doc.text(formatCurrency(avgValue), 150, sumY);

  drawFooter(doc, adminName);
  return doc;
};


// --- INVENTORY REPORT ---
export const generateInventoryReportPDF = async (inventoryData, startDate, endDate, adminName) => {
  const doc = new jsPDF();
  const logoDataUrl = await loadImageAsDataURL(logoUrl);
  
  let yPos = drawReportHeader(doc, 'Inventory Report', `Status as of: ${formatDate(endDate)}`, logoDataUrl);

  const cols = {
    name: { x: 15, align: 'left' },
    category: { x: 80, align: 'left' },
    brand: { x: 115, align: 'left' },
    qty: { x: 155, align: 'right' },
    status: { x: 195, align: 'right' }
  };

  const drawHeader = (y) => {
    doc.setFillColor(THEME.primary);
    doc.rect(15, y, 180, 8, 'F');
    doc.setTextColor(THEME.white);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    
    doc.text('Product Name', cols.name.x + 2, y + 5.5);
    doc.text('Category', cols.category.x, y + 5.5);
    doc.text('Brand', cols.brand.x, y + 5.5);
    doc.text('Stock', cols.qty.x, y + 5.5, { align: 'right' });
    doc.text('Status', cols.status.x, y + 5.5, { align: 'right' });
  };

  drawHeader(yPos);
  yPos += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);

  inventoryData.forEach((item, index) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
      drawHeader(yPos);
      yPos += 8;
    }

    if (index % 2 === 0) {
      doc.setFillColor(THEME.accent);
      doc.rect(15, yPos, 180, 7, 'F');
    }

    const name = item.productName.length > 30 ? item.productName.substring(0, 27) + '...' : item.productName;

    doc.setTextColor(THEME.text);
    doc.setFont('helvetica', 'normal');
    
    doc.text(name, cols.name.x + 2, yPos + 5);
    doc.text(item.category || '-', cols.category.x, yPos + 5);
    doc.text(item.brand || '-', cols.brand.x, yPos + 5);
    doc.text(item.currentStock.toString(), cols.qty.x, yPos + 5, { align: 'right' });

    // Conditional Formatting for Status
    if (item.stockStatus === 'Low Stock' || item.stockStatus === 'Out of Stock') {
      doc.setTextColor('#e74c3c'); // Red
      doc.setFont('helvetica', 'bold');
    } else {
      doc.setTextColor('#27ae60'); // Green
    }
    doc.text(item.stockStatus, cols.status.x, yPos + 5, { align: 'right' });

    yPos += 7;
  });

  // Summary
  yPos += 10;
  if (yPos > 250) { doc.addPage(); yPos = 20; }

  const totalStock = inventoryData.reduce((a, b) => a + b.currentStock, 0);
  const lowStock = inventoryData.filter(i => i.stockStatus === 'Low Stock').length;

  doc.setFillColor(THEME.primary);
  doc.rect(15, yPos, 180, 1, 'F'); // Thin separator line
  yPos += 10;

  doc.setFontSize(11);
  doc.setTextColor(THEME.text);
  doc.text(`Total SKU Count: ${inventoryData.length}`, 15, yPos);
  doc.text(`Total Units in Stock: ${totalStock}`, 80, yPos);
  
  doc.setTextColor('#e74c3c');
  doc.text(`Low Stock Alerts: ${lowStock}`, 150, yPos);

  drawFooter(doc, adminName);
  return doc;
};


// --- RETURNS REPORT ---
export const generateReturnsReportPDF = async (returnsData, startDate, endDate, adminName) => {
  const doc = new jsPDF();
  const logoDataUrl = await loadImageAsDataURL(logoUrl);

  let yPos = drawReportHeader(doc, 'Returns Report', `${formatDate(startDate)} - ${formatDate(endDate)}`, logoDataUrl);

  const cols = {
    id: { x: 15, align: 'left' },
    order: { x: 40, align: 'left' },
    customer: { x: 70, align: 'left' },
    reason: { x: 120, align: 'left' },
    amount: { x: 195, align: 'right' }
  };

  const drawHeader = (y) => {
    doc.setFillColor(THEME.primary);
    doc.rect(15, y, 180, 8, 'F');
    doc.setTextColor(THEME.white);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text('Return ID', cols.id.x + 2, y + 5.5);
    doc.text('Order Ref', cols.order.x, y + 5.5);
    doc.text('Customer', cols.customer.x, y + 5.5);
    doc.text('Reason', cols.reason.x, y + 5.5);
    doc.text('Refund Amt', cols.amount.x, y + 5.5, { align: 'right' });
  };

  drawHeader(yPos);
  yPos += 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);

  let totalRefund = 0;

  returnsData.forEach((item, index) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
      drawHeader(yPos);
      yPos += 8;
    }

    if (index % 2 === 0) {
      doc.setFillColor(THEME.accent);
      doc.rect(15, yPos, 180, 7, 'F');
    }

    doc.setTextColor(THEME.text);
    const customer = item.customer_name?.length > 20 ? item.customer_name.substring(0, 18) + '..' : item.customer_name;
    const reason = item.return_reason || 'N/A';

    doc.text(String(item.return_id), cols.id.x + 2, yPos + 5);
    doc.text(String(item.sale_number), cols.order.x, yPos + 5);
    doc.text(customer, cols.customer.x, yPos + 5);
    doc.text(reason, cols.reason.x, yPos + 5);
    
    const amt = Number(item.refund_amount) || 0;
    totalRefund += amt;
    doc.text(formatCurrency(amt), cols.amount.x, yPos + 5, { align: 'right' });

    yPos += 7;
  });

  yPos += 5;
  doc.setFont('helvetica', 'bold');
  doc.text('Total Refunded:', 150, yPos, { align: 'right' });
  doc.text(formatCurrency(totalRefund), 195, yPos, { align: 'right' });

  drawFooter(doc, adminName);
  return doc;
};


// --- RECEIPT (Modern Invoice Style) ---
export const generateSaleReceipt = async ({
  saleNumber,
  customerName,
  items = [],
  totalAmount = 0,
  paymentMethod = 'Cash',
  tenderedAmount = 0,
  changeAmount = 0,
  address = '',
  shippingOption = 'In-Store Pickup',
  createdAt = new Date()
}) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' }); // Switched to mm for consistency
  const pageWidth = 210;
  let y = 15;
  
  const logoDataUrl = await loadImageAsDataURL(logoUrl);

  // 1. Header Section (Logo + Company Info)
  if (logoDataUrl) {
    doc.addImage(logoDataUrl, 'PNG', 15, y, 25, 18);
  }
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(THEME.primary);
  doc.text('TJC AUTO SUPPLY', 200, y + 5, { align: 'right' });
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(THEME.lightText);
  doc.text('General Hizon Avenue, Santa Lucia', 200, y + 10, { align: 'right' });
  doc.text('San Fernando, Pampanga', 200, y + 14, { align: 'right' });
  doc.text('tjautosupply@gmail.com | 0912 345 6789', 200, y + 18, { align: 'right' });

  y += 30;

  // 2. Invoice Details Box
  doc.setDrawColor(THEME.line);
  doc.setFillColor(THEME.accent);
  doc.roundedRect(15, y, 180, 25, 2, 2, 'F');
  
  doc.setTextColor(THEME.text);
  doc.setFontSize(10);
  
  // Left Side (Bill To)
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 20, y + 6);
  doc.setFont('helvetica', 'normal');
  doc.text(customerName || 'Walk-in Customer', 20, y + 12);
  const addr = address ? address.substring(0, 40) : shippingOption;
  doc.setFontSize(9);
  doc.setTextColor(THEME.lightText);
  doc.text(addr, 20, y + 17);

  // Right Side (Invoice Info)
  doc.setTextColor(THEME.text);
  doc.setFontSize(10);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Receipt #:', 140, y + 6);
  doc.text('Date:', 140, y + 12);
  doc.text('Payment:', 140, y + 18);

  doc.setFont('helvetica', 'normal');
  doc.text(String(saleNumber), 190, y + 6, { align: 'right' });
  doc.text(new Date(createdAt).toLocaleDateString(), 190, y + 12, { align: 'right' });
  doc.text(paymentMethod, 190, y + 18, { align: 'right' });

  y += 35;

  // 3. Item Table
  const cols = {
    desc: { x: 15, w: 90 },
    qty: { x: 130, w: 20 },
    price: { x: 160, w: 25 },
    total: { x: 195, w: 25 }
  };

  // Table Header
  doc.setFillColor(THEME.primary);
  doc.rect(15, y, 180, 8, 'F');
  doc.setTextColor(THEME.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Item Description', cols.desc.x + 2, y + 5.5);
  doc.text('Qty', cols.qty.x, y + 5.5, { align: 'center' });
  doc.text('Price', cols.price.x, y + 5.5, { align: 'right' });
  doc.text('Amount', cols.total.x, y + 5.5, { align: 'right' });

  y += 8;

  // Items
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(THEME.text);

  items.forEach((it, index) => {
    // Page Break
    if (y > 260) { doc.addPage(); y = 20; }

    if (index % 2 === 0) {
      doc.setFillColor(THEME.accent);
      doc.rect(15, y, 180, 8, 'F');
    }

    const name = it.productName || it.name || '';
    const qty = Number(it.quantity);
    const price = Number(it.price || it.unitPrice);
    const total = qty * price;

    // Name might be long, handle basic truncation
    const displayName = name.length > 45 ? name.substring(0, 42) + '...' : name;

    doc.text(displayName, cols.desc.x + 2, y + 5.5);
    doc.text(String(qty), cols.qty.x, y + 5.5, { align: 'center' });
    doc.text(formatCurrency(price).replace('PHP', ''), cols.price.x, y + 5.5, { align: 'right' });
    doc.text(formatCurrency(total).replace('PHP', ''), cols.total.x, y + 5.5, { align: 'right' });

    // If serials exist, print below in small italic
    const serials = it.serialNumbers || it.serial_numbers || [];
    if (serials.length > 0) {
      y += 5;
      doc.setFontSize(7);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(THEME.lightText);
      doc.text(`SN: ${serials.join(', ')}`, cols.desc.x + 5, y + 5.5);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(THEME.text);
      y += 3; // extra spacing
    }

    y += 8;
  });

  y += 5;

  // 4. Totals Section
  const totalBoxX = 120;
  const totalBoxW = 75;
  
  doc.setDrawColor(THEME.line);
  doc.line(15, y, 195, y); // Separator line
  y += 5;

  // Subtotal / Totals
  const drawTotalLine = (label, value, isBold = false, isGrand = false) => {
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.setFontSize(isGrand ? 12 : 10);
    doc.setTextColor(isGrand ? THEME.primary : THEME.text);
    
    doc.text(label, totalBoxX, y + 5);
    doc.text(value, 195, y + 5, { align: 'right' });
    y += isGrand ? 10 : 6;
  };

  drawTotalLine('Subtotal:', formatCurrency(totalAmount));
  
  if (tenderedAmount > 0 && paymentMethod === 'Cash') {
    drawTotalLine('Cash Tendered:', formatCurrency(tenderedAmount));
    drawTotalLine('Change:', formatCurrency(changeAmount));
  }

  y += 2;
  // Grand Total Bar
  doc.setFillColor(THEME.primary);
  doc.rect(totalBoxX - 5, y, totalBoxW + 5, 10, 'F');
  doc.setTextColor(THEME.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('TOTAL', totalBoxX, y + 7);
  doc.text(formatCurrency(totalAmount), 195, y + 7, { align: 'right' });

  // 5. Footer
  const footerY = 280;
  doc.setFontSize(8);
  doc.setTextColor(THEME.lightText);
  doc.setFont('helvetica', 'normal');
  doc.text('Thank you for your business!', pageWidth / 2, footerY, { align: 'center' });
  doc.text('Returns accepted within 7 days with receipt.', pageWidth / 2, footerY + 4, { align: 'center' });

  return doc;
};